//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.5485
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using System.Security.Cryptography.X509Certificates;
using System.Net.Security;
using System.Net;




// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "GateServiceSOAP11Binding", Namespace = "https://bramka.e-deklaracje.mf.gov.pl/")]
public partial class GateService : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback sendDocumentOperationCompleted;

    private System.Threading.SendOrPostCallback sendUnsignDocumentOperationCompleted;

    private System.Threading.SendOrPostCallback sendDocumentWithAttachmentOperationCompleted;

    private System.Threading.SendOrPostCallback requestUPOOperationCompleted;

    /// <remarks/>
    public GateService()
    {
        ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };

        this.Timeout = 60000;  
    }


    /// <remarks/>
    public event sendDocumentCompletedEventHandler sendDocumentCompleted;

    /// <remarks/>
    public event sendUnsignDocumentCompletedEventHandler sendUnsignDocumentCompleted;

    /// <remarks/>
    public event sendDocumentWithAttachmentCompletedEventHandler sendDocumentWithAttachmentCompleted;

    /// <remarks/>
    public event requestUPOCompletedEventHandler requestUPOCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sendDocument", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("sendDocumentResponse", Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]
    public sendDocumentResponse sendDocument([System.Xml.Serialization.XmlElementAttribute("sendDocument", Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")] sendDocument sendDocument1)
    {
        object[] results = this.Invoke("sendDocument", new object[] {
                    sendDocument1});
        return ((sendDocumentResponse)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginsendDocument(sendDocument sendDocument1, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("sendDocument", new object[] {
                    sendDocument1}, callback, asyncState);
    }

    /// <remarks/>
    public sendDocumentResponse EndsendDocument(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((sendDocumentResponse)(results[0]));
    }

    /// <remarks/>
    public void sendDocumentAsync(sendDocument sendDocument1)
    {
        this.sendDocumentAsync(sendDocument1, null);
    }

    /// <remarks/>
    public void sendDocumentAsync(sendDocument sendDocument1, object userState)
    {
        if ((this.sendDocumentOperationCompleted == null))
        {
            this.sendDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendDocumentOperationCompleted);
        }
        this.InvokeAsync("sendDocument", new object[] {
                    sendDocument1}, this.sendDocumentOperationCompleted, userState);
    }

    private void OnsendDocumentOperationCompleted(object arg)
    {
        if ((this.sendDocumentCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sendDocumentCompleted(this, new sendDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sendUnsignDocument", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("sendUnsignDocumentResponse", Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]
    public sendUnsignDocumentResponse sendUnsignDocument([System.Xml.Serialization.XmlElementAttribute("sendUnsignDocument", Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")] sendUnsignDocument sendUnsignDocument1)
    {
        object[] results = this.Invoke("sendUnsignDocument", new object[] {
                    sendUnsignDocument1});
        return ((sendUnsignDocumentResponse)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginsendUnsignDocument(sendUnsignDocument sendUnsignDocument1, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("sendUnsignDocument", new object[] {
                    sendUnsignDocument1}, callback, asyncState);
    }

    /// <remarks/>
    public sendUnsignDocumentResponse EndsendUnsignDocument(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((sendUnsignDocumentResponse)(results[0]));
    }

    /// <remarks/>
    public void sendUnsignDocumentAsync(sendUnsignDocument sendUnsignDocument1)
    {
        this.sendUnsignDocumentAsync(sendUnsignDocument1, null);
    }

    /// <remarks/>
    public void sendUnsignDocumentAsync(sendUnsignDocument sendUnsignDocument1, object userState)
    {
        if ((this.sendUnsignDocumentOperationCompleted == null))
        {
            this.sendUnsignDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendUnsignDocumentOperationCompleted);
        }
        this.InvokeAsync("sendUnsignDocument", new object[] {
                    sendUnsignDocument1}, this.sendUnsignDocumentOperationCompleted, userState);
    }

    private void OnsendUnsignDocumentOperationCompleted(object arg)
    {
        if ((this.sendUnsignDocumentCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sendUnsignDocumentCompleted(this, new sendUnsignDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sendDocumentWithAttachment", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("sendDocumentWithAttachmentResponse", Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]
    public sendDocumentWithAttachmentResponse sendDocumentWithAttachment([System.Xml.Serialization.XmlElementAttribute("sendDocumentWithAttachment", Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")] sendDocumentWithAttachment sendDocumentWithAttachment1)
    {
        object[] results = this.Invoke("sendDocumentWithAttachment", new object[] {
                    sendDocumentWithAttachment1});
        return ((sendDocumentWithAttachmentResponse)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginsendDocumentWithAttachment(sendDocumentWithAttachment sendDocumentWithAttachment1, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("sendDocumentWithAttachment", new object[] {
                    sendDocumentWithAttachment1}, callback, asyncState);
    }

    /// <remarks/>
    public sendDocumentWithAttachmentResponse EndsendDocumentWithAttachment(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((sendDocumentWithAttachmentResponse)(results[0]));
    }

    /// <remarks/>
    public void sendDocumentWithAttachmentAsync(sendDocumentWithAttachment sendDocumentWithAttachment1)
    {
        this.sendDocumentWithAttachmentAsync(sendDocumentWithAttachment1, null);
    }

    /// <remarks/>
    public void sendDocumentWithAttachmentAsync(sendDocumentWithAttachment sendDocumentWithAttachment1, object userState)
    {
        if ((this.sendDocumentWithAttachmentOperationCompleted == null))
        {
            this.sendDocumentWithAttachmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendDocumentWithAttachmentOperationCompleted);
        }
        this.InvokeAsync("sendDocumentWithAttachment", new object[] {
                    sendDocumentWithAttachment1}, this.sendDocumentWithAttachmentOperationCompleted, userState);
    }

    private void OnsendDocumentWithAttachmentOperationCompleted(object arg)
    {
        if ((this.sendDocumentWithAttachmentCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sendDocumentWithAttachmentCompleted(this, new sendDocumentWithAttachmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:requestUPO", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("requestUPOResponse", Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]    
    public requestUPOResponse requestUPO([System.Xml.Serialization.XmlElementAttribute("requestUPO", Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")] requestUPO requestUPO1)
    {
        object[] results = this.Invoke("requestUPO", new object[] {
                    requestUPO1});
        return ((requestUPOResponse)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginrequestUPO(requestUPO requestUPO1, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("requestUPO", new object[] {
                    requestUPO1}, callback, asyncState);
    }

    /// <remarks/>
    public requestUPOResponse EndrequestUPO(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((requestUPOResponse)(results[0]));
    }

    /// <remarks/>
    public void requestUPOAsync(requestUPO requestUPO1)
    {
        this.requestUPOAsync(requestUPO1, null);
    }

    /// <remarks/>
    public void requestUPOAsync(requestUPO requestUPO1, object userState)
    {
        if ((this.requestUPOOperationCompleted == null))
        {
            this.requestUPOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrequestUPOOperationCompleted);
        }
        this.InvokeAsync("requestUPO", new object[] {
                    requestUPO1}, this.requestUPOOperationCompleted, userState);
    }

    private void OnrequestUPOOperationCompleted(object arg)
    {
        if ((this.requestUPOCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.requestUPOCompleted(this, new requestUPOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]
public partial class sendDocument
{

    private byte[] documentField;

    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] document
    {
        get
        {
            return this.documentField;
        }
        set
        {
            this.documentField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]
public partial class sendDocumentResponse
{

    private string refIdField;

    private int statusField;

    private string statusOpisField;

    /// <uwagi/>
    public string refId
    {
        get
        {
            return this.refIdField;
        }
        set
        {
            this.refIdField = value;
        }
    }

    /// <uwagi/>
    public int status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <uwagi/>
    public string statusOpis
    {
        get
        {
            return this.statusOpisField;
        }
        set
        {
            this.statusOpisField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]
public partial class sendUnsignDocument
{

    private byte[] documentField;

    private sendUnsignDocumentLanguage languageField;

    private bool languageFieldSpecified;

    private sendUnsignDocumentSignatureType signatureTypeField;

    private bool signatureTypeFieldSpecified;

    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] document
    {
        get
        {
            return this.documentField;
        }
        set
        {
            this.documentField = value;
        }
    }

    /// <uwagi/>
    public sendUnsignDocumentLanguage language
    {
        get
        {
            return this.languageField;
        }
        set
        {
            this.languageField = value;
        }
    }

    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool languageSpecified
    {
        get
        {
            return this.languageFieldSpecified;
        }
        set
        {
            this.languageFieldSpecified = value;
        }
    }

    /// <uwagi/>
    public sendUnsignDocumentSignatureType signatureType
    {
        get
        {
            return this.signatureTypeField;
        }
        set
        {
            this.signatureTypeField = value;
        }
    }

    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool signatureTypeSpecified
    {
        get
        {
            return this.signatureTypeFieldSpecified;
        }
        set
        {
            this.signatureTypeFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]
public enum sendUnsignDocumentLanguage
{

    /// <uwagi/>
    de,

    /// <uwagi/>
    en,

    /// <uwagi/>
    pl,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]
public enum sendUnsignDocumentSignatureType
{

    /// <uwagi/>
    PIT,

    /// <uwagi/>
    MPO,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]
public partial class sendUnsignDocumentResponse
{

    private string refIdField;

    private int statusField;

    private string statusOpisField;

    /// <uwagi/>
    public string refId
    {
        get
        {
            return this.refIdField;
        }
        set
        {
            this.refIdField = value;
        }
    }

    /// <uwagi/>
    public int status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <uwagi/>
    public string statusOpis
    {
        get
        {
            return this.statusOpisField;
        }
        set
        {
            this.statusOpisField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]
public partial class sendDocumentWithAttachment
{

    private byte[] attachmentField;

    private byte[] documentField;

    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] attachment
    {
        get
        {
            return this.attachmentField;
        }
        set
        {
            this.attachmentField = value;
        }
    }

    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
    public byte[] document
    {
        get
        {
            return this.documentField;
        }
        set
        {
            this.documentField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]
public partial class sendDocumentWithAttachmentResponse
{

    private string refIdField;

    private int statusField;

    private string statusOpisField;

    /// <uwagi/>
    public string refId
    {
        get
        {
            return this.refIdField;
        }
        set
        {
            this.refIdField = value;
        }
    }

    /// <uwagi/>
    public int status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <uwagi/>
    public string statusOpis
    {
        get
        {
            return this.statusOpisField;
        }
        set
        {
            this.statusOpisField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]
public partial class requestUPO
{

    private string refIdField;

    private requestUPOLanguage languageField;

    private bool languageFieldSpecified;

    /// <uwagi/>
    public string refId
    {
        get
        {
            return this.refIdField;
        }
        set
        {
            this.refIdField = value;
        }
    }

    /// <uwagi/>
    public requestUPOLanguage language
    {
        get
        {
            return this.languageField;
        }
        set
        {
            this.languageField = value;
        }
    }

    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool languageSpecified
    {
        get
        {
            return this.languageFieldSpecified;
        }
        set
        {
            this.languageFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]
public enum requestUPOLanguage
{

    /// <uwagi/>
    de,

    /// <uwagi/>
    en,

    /// <uwagi/>
    pl,
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://bramka.e-deklaracje.mf.gov.pl/xsd")]
public partial class requestUPOResponse
{

    private string upoField;

    private int statusField;

    private string statusOpisField;

    /// <uwagi/>
    public string upo
    {
        get
        {
            return this.upoField;
        }
        set
        {
            this.upoField = value;
        }
    }

    /// <uwagi/>
    public int status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <uwagi/>
    public string statusOpis
    {
        get
        {
            return this.statusOpisField;
        }
        set
        {
            this.statusOpisField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sendDocumentCompletedEventHandler(object sender, sendDocumentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sendDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal sendDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public sendDocumentResponse Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((sendDocumentResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sendUnsignDocumentCompletedEventHandler(object sender, sendUnsignDocumentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sendUnsignDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal sendUnsignDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public sendUnsignDocumentResponse Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((sendUnsignDocumentResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void sendDocumentWithAttachmentCompletedEventHandler(object sender, sendDocumentWithAttachmentCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sendDocumentWithAttachmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal sendDocumentWithAttachmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public sendDocumentWithAttachmentResponse Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((sendDocumentWithAttachmentResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
public delegate void requestUPOCompletedEventHandler(object sender, requestUPOCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class requestUPOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal requestUPOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public requestUPOResponse Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((requestUPOResponse)(this.results[0]));
        }
    }
}
